# Default values for mtproto-proxy
# This file contains values that can be overridden during helm install

replicaCount: 1

image:
  repository: telegrammessenger/proxy
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 443

ingress:
  enabled: true
  annotations:
    # Add annotations for external proxying, e.g., for Warp WG or other proxies
    # Uncomment and customize as needed for your environment
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/configuration-snippet: |-
    #   proxy_set_header X-Forwarded-Proto $scheme;
  hosts:
    - host: mtproto-proxy.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

affinity: {}

tolerations: [] 