apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mtproto-proxy.fullname" . }}
  labels:
    {{- include "mtproto-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mtproto-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mtproto-proxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 443
              protocol: TCP
          env:
            {{- if .Values.env.SECRET }}
            - name: SECRET
              value: {{ .Values.env.SECRET }}
            {{- end }}
            {{- if .Values.env.TAG }}
            - name: TAG
              value: {{ .Values.env.TAG }}
            {{- end }}
            {{- if .Values.env.WORKERS }}
            - name: WORKERS
              value: {{ .Values.env.WORKERS | quote }}
            {{- end }}
            {{- if .Values.env.SECRET_COUNT }}
            - name: SECRET_COUNT
              value: {{ .Values.env.SECRET_COUNT | quote }}
            {{- end }}