apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mtproto-proxy.fullname" . }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}  # Use from values if defined
  tls:
    {{- if .Values.ingress.tls }}
    {{- toYaml .Values.ingress.tls | nindent 4 }}
    {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "mtproto-proxy.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }} 